apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-secret
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  roles:
    - name: test1
    - name: test2
    - name: test5
  client:
    clientId: client-secret
    secret: client-secret
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    defaultRoles:
      - test1
      - test2
      - test5