// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type KeycloakExpansion interface{}

type KeycloakBackupExpansion interface{}

type KeycloakClientExpansion interface{}

type KeycloakRealmExpansion interface{}

type KeycloakUserExpansion interface{}
