apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  test.properties: |
    blah=true
---
apiVersion: v1
kind: Secret
metadata:
  name: keytabs
data:
  krb5.keytab: RkFLRSBLRVlUQUIK
---
apiVersion: v1
kind: Secret
metadata:
  name: realm1
stringData:
  realm1_bindcred: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: realm2
stringData:
  realm2_bindcred: "password"
---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: True
  keycloakDeploymentSpec:
    experimental:
      args:
        - "-Djboss.as.management.blocking.timeout=600"
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "false"
      volumes:
        defaultMode: 0777
        items:
          - name: keytab
            mountPath: /keytabs
            secrets:
              - keytab
          - name: vault
            mountPath: /opt/jboss/keycloak/secrets
            secrets:
              - realm1
              - realm2
          - name: test-config
            mountPath: /configmap
            configMaps:
              - test-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - keycloak
              topologyKey: "topology.kubernetes.io/zone"
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - keycloak
              topologyKey: "kubernetes.io/hostname"
