---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-vault
type: Opaque
stringData:
  ldap-realm_bindCredential: "test-password"
---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: True
  keycloakDeploymentSpec:
    experimental:
      volumes:
        defaultMode: 0777
        items:
          - name: vault
            mountPath: /opt/jboss/keycloak/secrets
            secrets:
              - keycloak-vault
