// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKeycloakGroups implements KeycloakGroupInterface
type FakeKeycloakGroups struct {
	Fake *FakeKeycloakV1alpha1
	ns   string
}

var keycloakgroupsResource = schema.GroupVersionResource{Group: "keycloak.org", Version: "v1alpha1", Resource: "keycloakgroups"}

var keycloakgroupsKind = schema.GroupVersionKind{Group: "keycloak.org", Version: "v1alpha1", Kind: "KeycloakGroup"}

// Get takes name of the keycloakGroup, and returns the corresponding keycloakGroup object, and an error if there is any.
func (c *FakeKeycloakGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KeycloakGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(keycloakgroupsResource, c.ns, name), &v1alpha1.KeycloakGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeycloakGroup), err
}

// List takes label and field selectors, and returns the list of KeycloakGroups that match those selectors.
func (c *FakeKeycloakGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KeycloakGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(keycloakgroupsResource, keycloakgroupsKind, c.ns, opts), &v1alpha1.KeycloakGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KeycloakGroupList{ListMeta: obj.(*v1alpha1.KeycloakGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.KeycloakGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested keycloakGroups.
func (c *FakeKeycloakGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(keycloakgroupsResource, c.ns, opts))

}

// Create takes the representation of a keycloakGroup and creates it.  Returns the server's representation of the keycloakGroup, and an error, if there is any.
func (c *FakeKeycloakGroups) Create(ctx context.Context, keycloakGroup *v1alpha1.KeycloakGroup, opts v1.CreateOptions) (result *v1alpha1.KeycloakGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(keycloakgroupsResource, c.ns, keycloakGroup), &v1alpha1.KeycloakGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeycloakGroup), err
}

// Update takes the representation of a keycloakGroup and updates it. Returns the server's representation of the keycloakGroup, and an error, if there is any.
func (c *FakeKeycloakGroups) Update(ctx context.Context, keycloakGroup *v1alpha1.KeycloakGroup, opts v1.UpdateOptions) (result *v1alpha1.KeycloakGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(keycloakgroupsResource, c.ns, keycloakGroup), &v1alpha1.KeycloakGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeycloakGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKeycloakGroups) UpdateStatus(ctx context.Context, keycloakGroup *v1alpha1.KeycloakGroup, opts v1.UpdateOptions) (*v1alpha1.KeycloakGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(keycloakgroupsResource, "status", c.ns, keycloakGroup), &v1alpha1.KeycloakGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeycloakGroup), err
}

// Delete takes name of the keycloakGroup and deletes it. Returns an error if one occurs.
func (c *FakeKeycloakGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(keycloakgroupsResource, c.ns, name), &v1alpha1.KeycloakGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKeycloakGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(keycloakgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KeycloakGroupList{})
	return err
}

// Patch applies the patch and returns the patched keycloakGroup.
func (c *FakeKeycloakGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KeycloakGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(keycloakgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.KeycloakGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeycloakGroup), err
}
