apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-claim
  labels:
    app: keycloak
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce