package model

import (
	kc "github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func KeycloakMasterRealm(cr *kc.Keycloak) *kc.KeycloakRealm {
	return &kc.KeycloakRealm{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "master",
			Namespace: cr.Namespace,
			Labels:    cr.Labels,
		},
		Spec: kc.KeycloakRealmSpec{
			InstanceSelector: &metav1.LabelSelector{
				MatchLabels: cr.Labels,
			},
			Realm: &kc.KeycloakAPIRealm{
				Realm:   "master",
				Enabled: true,
			},
			Managed: kc.Autogenerated,
		},
	}
}

func KeycloakMasterRealmSelector(cr *kc.Keycloak) client.ObjectKey {
	return client.ObjectKey{
		Name:      "master",
		Namespace: cr.Namespace,
	}
}

func KeycloakMasterRealmReconciled(cr *kc.Keycloak, currentState *kc.KeycloakRealm) *kc.KeycloakRealm {
	reconciled := currentState.DeepCopy()
	reconciled.Spec.Realm.Realm = "master"
	return reconciled
}
