// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// KeycloakListerExpansion allows custom methods to be added to
// KeycloakLister.
type KeycloakListerExpansion interface{}

// KeycloakNamespaceListerExpansion allows custom methods to be added to
// KeycloakNamespaceLister.
type KeycloakNamespaceListerExpansion interface{}

// KeycloakBackupListerExpansion allows custom methods to be added to
// KeycloakBackupLister.
type KeycloakBackupListerExpansion interface{}

// KeycloakBackupNamespaceListerExpansion allows custom methods to be added to
// KeycloakBackupNamespaceLister.
type KeycloakBackupNamespaceListerExpansion interface{}

// KeycloakClientListerExpansion allows custom methods to be added to
// KeycloakClientLister.
type KeycloakClientListerExpansion interface{}

// KeycloakClientNamespaceListerExpansion allows custom methods to be added to
// KeycloakClientNamespaceLister.
type KeycloakClientNamespaceListerExpansion interface{}

// KeycloakRealmListerExpansion allows custom methods to be added to
// KeycloakRealmLister.
type KeycloakRealmListerExpansion interface{}

// KeycloakRealmNamespaceListerExpansion allows custom methods to be added to
// KeycloakRealmNamespaceLister.
type KeycloakRealmNamespaceListerExpansion interface{}

// KeycloakUserListerExpansion allows custom methods to be added to
// KeycloakUserLister.
type KeycloakUserListerExpansion interface{}

// KeycloakUserNamespaceListerExpansion allows custom methods to be added to
// KeycloakUserNamespaceLister.
type KeycloakUserNamespaceListerExpansion interface{}
